### ISSUE TITLE
Game bookings/requests can overlap in time

### ISSUE THREAD

**Issue by Oscariremma** [GAsplund/GAMES#122]
Currently multiple game bookings for the same game can be active simultaneously.

This should be prevented in the backend

**Comment by GAsplund** [comment]
Strange, there should already be functionality in place to prevent this from happening. Perhaps we are being too strict on what is a valid request?

**Comment by Oscariremma** [comment]
![image](https://github.com/GAsplund/GAMES/assets/16071372/0f0f7289-7140-446c-ad01-edfaa6012e63)
We will have to investigate a bit to see where it goes thru, but might be tight on time this week
