### ISSUE TITLE
As a user of GAMES, I want to be able to read about how the application works, so that I can learn how to use or modify it

### ISSUE THREAD

**Issue by GAsplund** [GAsplund/GAMES#21]
- [ ] Define a good framework/format for writing documentation in code
- [ ] Define a way of exporting using said format to an acceptable file format (PDF or HTML?)

**Comment by x183** [comment]
Shouldn't a user story be about someone other than the developer?

**Comment by GAsplund** [comment]
In our last project, we used "As a [internal development position], ..." frequently to describe tasks that are difficult or don't make sense describe from an end-user standpoint. With that said, you are correct in that a user story should be written from the perspective of the end-user.

I will try and come up with a user story that's written from a more correct perspective, but any suggestions are also welcome.

**Comment by GAsplund** [comment]
The title has been changed, and the "sub-goals" have been clarified so that the user story has a clearer definition of completion.

**Comment by Supergamer1337** [comment]
The only thing I found, at least for our end that seems to do... Something like it, is [tsoa](https://tsoa-community.github.io/docs/), but it feels like it makes writing the api a bit more boiler-platey that it needs to be. Similarily, it does make writing the code more object-oriented which, at least in my personal experience, is not really the standard way to write TS backend code nowadays.

**Comment by GAsplund** [comment]
In order to interfere/interact as little with as possible with the code, documentation could be done in comments instead. I found [apiDoc](https://apidocjs.com/), which is documented in a similar fashion to TSDoc. This can then in turn be exported to [OpenAPI](https://www.npmjs.com/package/apidoc-openapi), or [Swagger](https://www.npmjs.com/package/apidoc-swagger-converter). Without having read much into how Actions work for publishing Pages websites, I hope that this can be used to export a static documentation site to be hosted by GitHub.
