### ISSUE TITLE
As a forgetful gamer, I want to be able mark games as played, so that I know if I've played it before

### ISSUE THREAD

**Issue by Krysset** [GAsplund/GAMES#74]
- [x] Save games played in database
- [x] Checkbox to fill, "Have you played this game?"

**Comment by x183** [comment]
It'd be nice to have a list of all played games on your profile, as well as some functionality in that list for searching and adding new played games 😀

**Comment by Krysset** [comment]
The first part is a part of the profile user story and the rest would probably be implemented in the already existing game list with new filters. It could be added to update the filter options and such but I feel that it's better to have it as a new user story

**Comment by x183** [comment]
> The first part is a part of the profile user story and the rest would probably be implemented in the already existing game list with new filters. It could be added to update the filter options and such but I feel that it's better to have it as a new user story

Yes, that seems reasonable :+1: :100:
![image](https://user-images.githubusercontent.com/55193662/235654534-cfae02ec-3ddc-4bae-89bf-076ae9799b5d.png)
